name: Run Hello Script

on:
  workflow_dispatch:  # manual 
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # ← add this


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pytz

      - name: Run script
        run: python hello.py